name: Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y nasm ninja-build lld python3 && \
           git clone https://github.com/limine-bootloader/limine -b v4.x-branch-binary $HOME/limine && \
           cd $HOME/limine && make && cd -
    - name: Build
      run: export LIMINE_PATH="$HOME/limine" && \
           ./gen.py && \
           ninja